core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),
]

payments/urls.py
from django.urls import path, re_path
from . import views

app_name = 'payments'

urlpatterns = [
    path("", views.show_payments, name="show_payments"),
    path("add-favorite/", views.add_favorite, name="add_favorite"),
    path("delete-favorite/<int:id>/", views.delete_favorite, name="delete_favorite"),
    re_path(r'^pix(?:/(?P<step>\w+))?/$', views.pix, name='pix'),
    path("depositos/", views.depositos, name="depositos"),
    path("extrato/", views.extrato, name="extrato"),
    path('register_pix/', views.register_pix, name='register_pix'),
]

payments/models.py
from django.db import models

from users.models import Client

# Create your models here.
class Pix(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE)
    type = models.CharField(max_length=255)
    key = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f"{self.type} - {self.key}"

class Payment(models.Model):
    sender = models.ForeignKey(Client, related_name='payments_sent', on_delete=models.CASCADE)
    receiver = models.ForeignKey(Client, related_name='payments_received', on_delete=models.CASCADE)
    value = models.FloatField()
    date = models.DateField(auto_now_add=True)
    pix = models.ForeignKey(Pix, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"Payment from {self.sender} to {self.receiver} of {self.value} on {self.date}"

class Favorite(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE)

    pix = models.ForeignKey(Pix, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"Favorite Pix {self.pix} for user {self.user}"

payments/views.py
import re
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.core.paginator import Paginator

from .services import get_payments, set_payment
from users.models import Client
from .models import Payment, Favorite, Pix

from decimal import Decimal


@login_required
def show_payments(request):
    if request.method == 'GET':
        payments_all = Payment.objects.filter(
            Q(receiver__user__id=request.user.id) | Q(sender__user__id=request.user.id)
        ).order_by('-date')
        user = Client.objects.get(user=request.user)
        favorites = Favorite.objects.filter(user=user)

        paginator = Paginator(payments_all, 3)
        page = request.GET.get('page', 1)
        payments = paginator.page(page)


        payments_list = Payment.objects.filter(id__in=[payment.id for payment in payments.object_list])

        payments.object_list = get_payments(request.user.client.id, payments_list)

        context = {
            'favorites': favorites,
            'payments': payments
        }

        return render(request, 'pagamentos.html', context=context)

@login_required
def add_favorite(request):
    key = request.POST.get('key')
    type = request.POST.get('type')

    pix = get_object_or_404(Pix, key=key)
    user = get_object_or_404(Client, user=request.user)
    print(user)

    favorite = Favorite(user=user, pix=pix)
    favorite.save()

    return redirect(reverse('payments:show_payments'))

@login_required
def delete_favorite(request, id):
    favorite = Favorite.objects.get(id=id)
    if request.user.id != favorite.user.user.id:
            return redirect(reverse('payments:show_payments'))
    favorite.delete()

    return redirect(reverse('payments:show_payments'))

@login_required
def pix(request, step=None):
    if step == 'select' or not step:
        return render(request, 'pix.html')
    elif step == 'finalizar':
        dados = request.session.get('dados')
        print(dados)
        if not dados:
            return redirect(reverse('payments:pix'))

        senha = request.POST.get('senha')
        user = Client.objects.get(user=request.user)
        if not user.user.check_password(senha):
            print("Errada")
            return render(request, 'pix_confirm.html', {'dados': dados})

        pix = Pix.objects.get(key=dados['chave'])

        set_payment(user.id, pix.user_id, dados['valor'], pix)

        # Clear session data after use
        del request.session['dados']

        return redirect(reverse('payments:show_payments'))

    chave = request.POST.get('chave')
    type = request.POST.get('radio')
    valor = request.POST.get('valor')

    try:
        pix = Pix.objects.get(key=chave)
        dados = {'chave': chave, 'type': type, 'valor': valor}
        request.session['dados'] = dados
        return render(request, 'pix_confirm.html')
    except Pix.DoesNotExist:
        return render(request, 'pix.html', {'error': 'Chave Pix não encontrada'})

@login_required
def depositos(request):
    if request.method == 'POST':
        user =  Client.objects.get(user = request.user)
        valor = request.POST.get('valor')
        senha = request.POST.get('senha')
        if user.user.check_password(senha):
            try:
                user.cash += Decimal(valor)
                user.save()
                return redirect(reverse('payments:show_payments'))
            except:
                pass
    return render(request, 'depositos.html')

@login_required
def extrato(request):
    if request.method == 'POST':
        payments = Payment.objects.filter(
            Q(receiver__user__id=request.user.id) | Q(sender__user__id=request.user.id)
        )

        search_query = request.POST.get('search', '').strip()
        order_by_date = request.POST.get('Data', None)
        order_by_name = request.POST.get('nomes', None)

        # Apply ordering by date
        if order_by_date:
            payments = payments.order_by(order_by_date)

        # Apply ordering by name
        if order_by_name:
            if order_by_name == 'ascending':
                payments = payments.order_by(order_by_date, 'sender__user__first_name') if order_by_date else payments.order_by('sender__user__first_name')
            elif order_by_name == 'descending':
                payments = payments.order_by(order_by_date, '-sender__user__first_name') if order_by_date else payments.order_by('-sender__user__first_name')

        if search_query != '':
            # Filter by user
            if (search_query.isnumeric()):
                # Find integer and float values and convert floats to intl pattern
                query_values = re.findall(r'(?<!\S)\d+(?:,\d+)?(?!\S)', search_query)
                float_values = [float(value.replace(',', '.')) for value in query_values]

                # Filter by float values
                payments = payments.filter(value__in=float_values)
            else:
                payments = payments.filter(
                    Q(sender__user__id=request.user.id) & Q(receiver__user__email__icontains=search_query) |
                    Q(sender__user__id=request.user.id) & Q(receiver__user__username__icontains=search_query) |
                    Q(sender__user__id=request.user.id) & Q(receiver__user__first_name__icontains=search_query) |
                    Q(sender__user__id=request.user.id) & Q(receiver__user__last_name__icontains=search_query) |
                    Q(receiver__user__id=request.user.id) & Q(sender__user__email__icontains=search_query) |
                    Q(receiver__user__id=request.user.id) & Q(sender__user__username__icontains=search_query) |
                    Q(receiver__user__id=request.user.id) & Q(sender__user__first_name__icontains=search_query) |
                    Q(receiver__user__id=request.user.id) & Q(sender__user__last_name__icontains=search_query)
                )

            

            # print(payments)

            # Filter by dates
            date_patterns = [
                r'\b\d{4}-\d{2}-\d{2}\b',  # YYYY-MM-DD
                r'\b\d{2}/\d{2}/\d{4}\b'   # DD/MM/YYYY
            ]
            for pattern in date_patterns:
                date_matches = re.findall(pattern, search_query)
                for date_str in date_matches:
                    try:
                        if '-' in date_str:
                            date_obj = datetime.strptime(date_str, '%Y-%m-%d').date()
                        else:
                            date_obj = datetime.strptime(date_str, '%d/%m/%Y').date()
                        payments = payments.filter(date=date_obj)
                    except ValueError:
                        pass

        payments = get_payments(request.user.client.id, payments)
    else:
        payments = get_payments(request.user.client.id)

    context = {
        'payments': payments
    }

    return render(request, 'extrato.html', context)

@login_required
def register_pix(request):
    if request.method == 'POST':
        key = request.POST.get('key')
        type = request.POST.get('type')
        user = request.user.client

        Pix.objects.create(user=user, key=key, type=type)

        return redirect(reverse('payments:show_payments'))

    return render(request, 'register_pix.html')

payments/templates/depositos.html
{%extends 'base.html'%}

{%block header%}
    <h1>Depósitos</h1>
{%endblock%}

{%block content%}
    <main class="flex flex-col justify-center items-center">
        <div class="bg-slate-800 p-16 m-8 flex flex-col gap-8 rounded-lg">
            <h2 class="text-2xl">Deposite com o <span class="text-teal-500 font-bold">Rocket</span> Bank</h2>
            <form action="." method="post" class="flex flex-col gap-8"> {% csrf_token %}
                <div class="flex flex-col justify-center items-center">
                    <label for="valor">Valor:</label>
                    <input type="text" id="valor" name="valor" class="w-full p-2 bg-slate-900 border border-opacity-60 border-stone-400 rounded">
                </div>
                <div class="flex flex-col justify-center items-center">
                    <label for="senha">Senha:</label>
                    <input type="password" name="senha" id="senha" class="w-full p-2 bg-slate-900 border border-opacity-60 border-stone-400 rounded">
                </div>
                <input class="bg-teal-500 text-black font-bold p-2 rounded hover:bg-teal-600 transition-colors w-full cursor-pointer" value="Fazer depósito" type="submit">
                <input type="reset" class="bg-teal-500 text-black font-bold p-2 rounded hover:bg-teal-600 transition-colors w-full cursor-pointer">
            </form>
        </div>
    </main>
{%endblock%}

payments/templates/extrato.html
{% extends 'base.html' %}

{% block header %}
<h1>Extrato</h1>
{% endblock %}

{% block content %}
<div class="flex justify-center items-center w-full h-full py-12">
  <div class="w-11/12 h-5/6 bg-slate-800 rounded-lg px-4 py-5 flex flex-col md:flex-row gap-12">
    <div class="w-full flex flex-col gap-4 h-screen">
      <div class="flex bg-slate-900 rounded-full py-1 px-2 gap-6">
        <img src="/static/assets/Vector.svg" class="relative inset-0" alt="Pesquisar">
        <form action="{% url 'payments:extrato' %}" class="w-full" method="post"> {% csrf_token %}
          <input class="w-full bg-slate-900" placeholder="Pesquise por datas, nomes, valores..." name="search"
            type="text">
        </form>
      </div>
      <div class="bg-slate-900 px-16 md:px-12 lg:px-16 py-2 rounded-lg h-full scroll-css">
        <ul class="flex flex-col gap-2">
          {% if payments %}
          {% for expense in payments.Expenses %}
          <li>
            <div class="flex justify-between mb-1">
              <p>{{ expense.date }}</p>
              <p>{{expense.receiver__user__first_name}} {{expense.receiver__user__last_name}}</p>
              <p class="text-red-500">Saída</p>
              <p>{{expense.value}} R$</p>
              <p>Chave: {{expense.pix__key}}</p>
            </div>
            <div class="w-full h-px bg-slate-900"></div>
          </li>
          {% endfor %}
          {% for income in payments.Incomes %}
          <li>
            <div class="flex justify-between mb-1">
              <p>{{ income.date }}</p>
              <p>{{income.sender__user__first_name}} {{income.sender__user__last_name}}</p>
              <p class="text-green-500">Entrada</p>
              <p>{{income.value}} R$</p>
              <p>Chave: {{income.pix__key}}</p>
            </div>
            <div class="w-full h-px bg-slate-900"></div>
          </li>
          {% endfor %}
          {% else %}
          <p>Nenhum pagamento foi realizado</p>
          {% endif %}
        </ul>
      </div>
    </div>
    <div class="w-full">
      <h2 class="text-2xl text-center">Filtros</h2>
      <form class="flex flex-col gap-5" method="post" action="{% url 'payments:extrato' %}">
        {% csrf_token %}
        <div class="flex flex-col gap-3">
          <label>Data</label>
          <div class="flex gap-4">
            <div><input type="radio" id="recentes" value="-date" class="hidden peer" name="Data"><label for="recentes"
                class="bg-slate-900 px-3 py-1 rounded-full peer-checked:bg-teal-500">Recentes</label></div>
            <div><input type="radio" id="antigos" value="date" class="hidden peer" name="Data"><label for="antigos"
                class="bg-slate-900 px-3 py-1 rounded-full peer-checked:bg-teal-500">Mais antigos</label></div>
          </div>
        </div>
        <div class="flex flex-col gap-3">
          <label>Ordem de Nomes</label>
          <div class="flex gap-4">
            <div><input type="radio" id="az" value="ascending" class="hidden peer" name="nomes"><label for="az"
                class="bg-slate-900 px-3 py-1 rounded-full peer-checked:bg-teal-500">De A-Z</label></div>
            <div><input type="radio" id="za" value="descending" class="hidden peer" name="nomes"><label for="za"
                class="bg-slate-900 px-3 py-1 rounded-full peer-checked:bg-teal-500">De Z-A</label></div>
          </div>
        </div>
        <div>
          <button class="py-1 w-full bg-teal-500 text-slate-950 rounded-full" type="submit">Aplicar Filtros</button>
        </div>
        <div>
          <button type="submit" class="py-1 w-full bg-red-500 text-slate-950 rounded-full" onclick="clearFilters()">Limpar Filtros</button>
        </div>
      </form>
    </div>
  </div>
</div>
<script>
  function clearFilters() {
    const radioButtons = document.querySelectorAll('input[type="radio"]');
    radioButtons.forEach(radio => {
      radio.checked = false;
    });
  }
</script>
{% endblock %}

payments/templates/pagamentos.html
{% extends 'base.html' %}

{% block header %}
<h1>Pagamentos</h1>
{% endblock %}

{% block content %}
<div class="flex justify-center gap-4 lg:gap-20 p-8 lg:p-16 flex-col md:flex-row">
  <div class="bg-slate-800 w-full lg:w-2/6 text-center p-12 flex flex-col gap-12 rounded-lg">
    <h2 class="text-2xl">
      <span class="text-teal-500">Saldo:</span> R${{ user.client.cash }}
    </h2>
    <div>
      <h2 class="text-2xl mb-1">Extrato</h2>
      <div class="w-full h-1 bg-slate-900"></div>
    </div>
    <div>
      <ul class="flex flex-col gap-2">
        {% if payments %}
        {% for expense in payments.object_list.Expenses %}
        <li>
          <div class="flex justify-between mb-1">
            <p>{{ expense.receiver__user__first_name }}</p>
            <p class="text-red-500">Saída</p>
            <p>{{ expense.value }} R$</p>
          </div>
          <div class="w-full h-px bg-slate-900"></div>
        </li>
        {% endfor %}
        {% for income in payments.object_list.Incomes %}
        <li>
          <div class="flex justify-between mb-1">
            <p>{{ income.sender__user__first_name }} {{ income.sender__user__last_name }}</p>
            <p class="text-green-500">Entrada</p>
            <p>{{ income.value }} R$</p>
          </div>
          <div class="w-full h-px bg-slate-900"></div>
        </li>
        {% endfor %}
        <div class="flex justify-center items-center">{% include 'pagination.html' with page_obj=payments %}</div>
        {% else %}
        <p>Nenhum pagamento foi realizado</p>
        {% endif %}
      </ul>
    </div>
    <div>
      <a href="{% url 'payments:extrato' %}" title="Visualizar extrato em tela cheia">
        <button class="bg-slate-900 px-3 py-px rounded-full hover:bg-slate-700">Visualizar em tela cheia</button>
      </a>
    </div>
  </div>
  <div class="lg:w-1/2 w-full flex flex-col gap-12">
    <div class="bg-slate-800 rounded-lg">
      <ul class="flex p-4 gap-6 items-center">
        <li><a href="{% url 'payments:pix' %}" title="Acessar Pix">
            <div class="h-full flex flex-col justify-between"><img src="/static/assets/ic_baseline-pix.svg" alt="Pix">
              <p>Pix</p>
            </div>
          </a>
        </li>
        <li><a href="{% url 'payments:depositos' %}" title="Acessar Depósito">
            <div class="flex flex-col justify-between"><img class="h-6" src="/static/assets/vaadin_money-deposit.svg"
                alt="Depósito">
              <p>Depósito</p>
            </div>
          </a>
        </li>
        <li><a href="{% url 'payments:register_pix' %}" title="Registrar Chave Pix">
            <div class="flex flex-col justify-between"><img class="h-6" src="/static/assets/ic_baseline-pix.svg"
                alt="Registrar Chave Pix">
              <p>Registrar Chave Pix</p>
            </div>
          </a>
        </li>
      </ul>
    </div>
    <div class="bg-slate-800 flex flex-col items-center gap-12 p-8 rounded-lg">
      <div class="w-1/2 text-center">
        <h2 class="text-2xl">Favoritos</h2>
        <div class="w-full h-1 bg-slate-900"></div>
      </div>
      <div class="w-full flex gap-8 px-2">
        <div class="w-1/2">
          <ul class="flex flex-col gap-2">
            {% for favorito in favorites %}
            <li class="flex flex-col">
              <div class="flex justify-between mb-1">
                <p>{{ favorito.pix.user.user.first_name }}</p>
                <a href="{% url 'payments:delete_favorite' favorito.id %}" title="Remover favorito"><button
                    class="bg-red-600 rounded-full px-2 py-px hover:bg-red-500">Remover</button></a>
              </div>
              <div class="w-full h-px bg-slate-900"></div>
            </li>
            {% endfor %}
          </ul>
        </div>
        <div class="w-1/2 flex justify-end">
          <div><button class="bg-slate-900 px-3 py-px rounded-ful l hover:bg-slate-700 duration-300" id="adicionar"
              onclick="mostrar()">Adicionar</button></div>
          <div id="modal" class="hidden w-full bg-slate-900 rounded-xl p-6">
            <h2 class="text-center text-xl mb-4">Novo favorito</h2>
            <form action="{% url 'payments:add_favorite' %}" method="post">
              {% csrf_token %}
              <div class="mb-2">
                <label for="Name">Nome</label>
                <input type="text" name="name" placeholder="Digite aqui"
                  class="bg-slate-800 px-2 py-1 rounded-lg w-full mt-1" required>
              </div>
              <div class="mb-2">
                <label for="key">Chave</label>
                <input type="text" name="key" placeholder="Digite aqui"
                  class="bg-slate-800 px-2 py-1 rounded-lg w-full mt-1" required>
              </div>
              <div>
                <label for="type">Tipo</label>
                <div>
                  <input type="radio" name="type" id="cpf" value="cpf" required>
                  <label for="cpf">CPF</label>
                </div>
                <div>
                  <input type="radio" name="type" id="tel" value="tel">
                  <label for="tel">Telefone</label>
                </div>
                <div>
                  <input type="radio" name="type" id="num" value="num">
                  <label for="num">Número da conta</label>
                </div>
              </div>
              <div class="mt-4 flex gap-2 justify-center">
                <input type="submit" value="Salvar"
                  class="rounded-full bg-teal-500 px-2 lg:px-4 py-1 text-slate-950 hover:bg-teal-400 cursor-pointer">
                <input type="reset" value="Cancelar"
                  class="rounded-full bg-red-600 px-4 py-1 text-slate-950 hover:bg-red-500 cursor-pointer"
                  onclick="esconder()">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function mostrar() {
    let modal = document.getElementById('modal')
    let adicionar = document.getElementById('adicionar')
    adicionar.classList.add('hidden')
    modal.classList.remove('hidden')
  }

  function esconder() {
    let modal = document.getElementById('modal')
    modal.classList.add('hidden')
    adicionar.classList.remove('hidden')
  }
</script>
{% endblock %}

payments/templates/pix.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<h1>Transferência Pix</h1>
{% endblock %}

{% block content %}
<main class="flex justify-around items-center p-2 py-20 text-slate-50">
  <!--ícone-->
  <div class="hidden md:block relative">
    <div class="h-2/3 w-2/3 rounded-full bg-sky-950 blur-2xl absolute translate-x-1/4 translate-y-1/4"></div>
    <img src="{% static 'assets/pix asset.svg' %}" alt="" class="relative inset-0">
  </div>
  </div>
  <!--Tela pix-->
  <form class="bg-slate-800 md:w-1/2 px-16 py-8 flex flex-col gap-20 rounded-lg"
    action="{% url 'payments:pix' step='para_confirm' %}" method="post">
    {% csrf_token %}
    <h1 class="text-4xl font-semibold text-center">Selecione a Chave</h1>
    <div class="flex flex-col justify-center items-center">
      <label for="chave" class="text-base mb-1 font-bold">Chave Pix</label>
      <input type="text" name="chave" id="chave"
        class="w-full p-2 bg-slate-900 border border-opacity-60 border-stone-400 rounded" required>
    </div>
    <div class="flex gap-4 justify-center items-center">
      <div class="flex flex-wrap">
        <input type="radio" name="radio" id="cpf" class="hidden peer/cpf" required>
        <label for="cpf"
          class="p-2 bg-slate-900 rounded-full w-full flex justify-center items-center my-2 cursor-pointer transition duration-300 hover:bg-teal-500 peer-checked/cpf:bg-teal-500">CPF</label>
        <input type="radio" name="radio" id="celular" class="hidden peer/celular">
        <label for="celular"
          class="p-2 bg-slate-900 rounded-full w-full flex justify-center items-center my-2 cursor-pointer transition duration-300 hover:bg-teal-500 peer-checked/celular:bg-teal-500">Celular</label>
      </div>
      <div class="flex flex-wrap">
        <input type="radio" name="radio" id="email" class="hidden peer/email">
        <label for="email"
          class="p-2 bg-slate-900 rounded-full w-full flex justify-center items-center my-2 cursor-pointer transition duration-300 hover:bg-teal-500 peer-checked/email:bg-teal-500">Email</label>
        <input type="radio" name="radio" id="key" class="hidden peer/chave">
        <label for="key"
          class="p-2 bg-slate-900 rounded-full w-full flex justify-center items-center my-2 cursor-pointer transition duration-300 hover:bg-teal-500 peer-checked/chave:bg-teal-500">Chave
          Aleatória</label>
      </div>
    </div>
    <div class="flex flex-col justify-center items-center">
      <label for="valor" class="text-base mb-1 font-bold">Valor</label>
      <input type="number" name="valor" id="valor"
        class="w-full p-2 bg-slate-900 border border-opacity-60 border-stone-400 rounded" required>
    </div>
    <div class="flex flex-col gap-6">
      <input type="submit" value="Avançar"
        class="bg-teal-500 text-black font-bold p-2 rounded hover:bg-teal-600 transition-colors cursor-pointer">
    </div>
    <div class="flex gap-2 justify-center items-center">
      <!--Duas bolinhas final da tela-->
      <div class="w-4 h-4 bg-teal-500 rounded-full"></div>
      <div class="w-4 h-4 bg-slate-900 rounded-full"></div>
    </div>
  </form>

</main>
{% endblock %}

payments/templates/register_pix.html
{% extends 'base.html' %}

{% block header %}
<h1>Registrar Chave Pix</h1>
{% endblock %}

{% block content %}
<div class="flex justify-center items-center w-full h-full py-12">
  <div class="w-11/12 h-5/6 bg-slate-800 rounded-lg px-4 py-5 flex flex-col gap-12">
    <form action="{% url 'payments:register_pix' %}" method="post" class="flex flex-col gap-4">
      {% csrf_token %}
      <div>
        <label for="key">Chave</label>
        <div class="flex">
          <input type="text" name="key" id="key" placeholder="Digite a chave Pix"
            class="bg-slate-900 px-2 py-2 rounded-l-lg w-full" required>
          <button type="button" id="regenerate-btn"
            class="bg-slate-900 px-2 py-2 ml-4 rounded-r-lg hover:bg-slate-700 hidden"
            onclick="generateRandomKey()">Regenerar</button>
        </div>
      </div>
      <div>
        <label for="type">Tipo</label>
        <div>
          <input type="radio" name="type" id="cpf" value="cpf" required onchange="updateKeyInput()">
          <label for="cpf">CPF</label>
        </div>
        <div>
          <input type="radio" name="type" id="tel" value="tel" onchange="updateKeyInput()">
          <label for="tel">Telefone</label>
        </div>
        <div>
          <input type="radio" name="type" id="email" value="email" onchange="updateKeyInput()">
          <label for="email">Email</label>
        </div>
        <div>
          <input type="radio" name="type" id="random" value="random" onchange="updateKeyInput()">
          <label for="random">Chave Aleatória</label>
        </div>
      </div>
      <div class="mt-4 flex gap-2 justify-center">
        <input type="submit" value="Registrar"
          class="rounded-full bg-teal-500 px-4 py-1 text-slate-950 hover:bg-teal-400 cursor-pointer">
        <input type="reset" value="Cancelar"
          class="rounded-full bg-red-600 px-4 py-1 text-slate-950 hover:bg-red-500 cursor-pointer">
      </div>
    </form>
  </div>
</div>
<script>
  let randomKey = "";

  function updateKeyInput() {
    const keyInput = document.getElementById('key');
    const regenerateBtn = document.getElementById('regenerate-btn');
    const cpfRadio = document.getElementById('cpf');
    const telRadio = document.getElementById('tel');
    const emailRadio = document.getElementById('email');
    const randomRadio = document.getElementById('random');

    if (cpfRadio.checked) {
      keyInput.placeholder = 'Digite o CPF';
      keyInput.type = 'text';
      keyInput.value = '';
      keyInput.oninput = formatCPF;
      regenerateBtn.classList.add('hidden');
    } else if (telRadio.checked) {
      keyInput.placeholder = 'Digite o Telefone';
      keyInput.type = 'tel';
      keyInput.value = '';
      keyInput.oninput = formatPhoneNumber;
      regenerateBtn.classList.add('hidden');
    } else if (emailRadio.checked) {
      keyInput.placeholder = 'Digite o Email';
      keyInput.type = 'email';
      keyInput.value = '';
      keyInput.oninput = null;
      regenerateBtn.classList.add('hidden');
    } else if (randomRadio.checked) {
      keyInput.placeholder = 'Chave Aleatória';
      keyInput.type = 'text';
      if (randomKey == '') generateRandomKey();
      keyInput.value = randomKey;
      keyInput.oninput = null;
      regenerateBtn.classList.remove('hidden');
    }
  }

  function generateRandomKey() {
    const keyInput = document.getElementById('key');
    randomKey = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
    keyInput.value = randomKey;
  }

  function formatCPF(event) {
    const input = event.target;
    let value = input.value.replace(/\D/g, '');
    if (value.length > 11) value = value.slice(0, 11);
    value = value.replace(/(\d{3})(\d)/, '$1.$2');
    value = value.replace(/(\d{3})(\d)/, '$1.$2');
    value = value.replace(/(\d{3})(\d{1,2})$/, '$1-$2');
    input.value = value;
  }

  function formatPhoneNumber(event) {
    const input = event.target;
    let value = input.value.replace(/\D/g, '');
    if (value.length > 11) value = value.slice(0, 11);
    value = value.replace(/(\d{2})(\d)/, '($1) $2');
    value = value.replace(/(\d{5})(\d)/, '$1-$2');
    input.value = value;
  }
</script>
{% endblock %}